# Generated by Django 4.1.7 on 2023-03-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField()),
                ('entry_date', models.DateField()),
                ('category', models.CharField(choices=[('p', 'programming'), ('i', 'interests'), ('l', 'life')], max_length=1)),
                ('author', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
            },
        ),
    ]
